clone_depth: 1
# Test against this version of Node.js
environment:
  nodejs_version: "7"

# Install scripts. (runs after repo cloning)
install:
  # Install the version of nodejs specified in the matrix
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run test:windows

# Don't actually build.
build: off

# build cache to preserve files/folders between builds
cache:
  - node_modules  # local npm modules
